server:
  port: 9992
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 36000
      routes:
        - id: service-ai
          uri: lb://service-ai
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1
        - id: topic-security
          uri: lb://topic-security
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=1   
        - id: service-topic
          uri: lb://service-topic
          predicates:
            - Path=/api/topic/**
          filters:
            - StripPrefix=1
# 安全配置
security:
  # # 验证码
  # captcha:
  #   enabled: true
  #   type: math
  # # 防止XSS攻击
  # xss:
  #   enabled: true
  #   excludeUrls:
  #     - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /api/security/user/login
      - /api/security/user/logout
      - /api/system/captchaImage
